//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeManager.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicSheets
    {
        public int SheetID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string SheetName { get; set; }
        public Nullable<int> GeneratedBy { get; set; }
        public Nullable<System.DateTime> GenerationDate { get; set; }
        public string SheetData { get; set; }
        public string FilePath { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Users Users { get; set; }
    }
}
