//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeManager.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignments()
        {
            this.AssignmentComments = new HashSet<AssignmentComments>();
        }
    
        public int AssignmentID { get; set; }
        public int CourseID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string AssignmentName { get; set; }
        public string AssignmentDescription { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public int CreatedBy { get; set; }
        public string Weight { get; set; }
        public int StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentComments> AssignmentComments { get; set; }
        public virtual Courses Courses { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual StudyModules StudyModules { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
