//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeManager.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatParticipants
    {
        public int ChatParticipantID { get; set; }
        public int ChatID { get; set; }
        public int UserID { get; set; }
    
        public virtual Chats Chats { get; set; }
        public virtual Users Users { get; set; }
    }
}
