//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeManager.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseMembers
    {
        public int CourseMemberID { get; set; }
        public int CourseID { get; set; }
        public int UserID { get; set; }
        public int CourseRoleID { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
    
        public virtual CourseRoles CourseRoles { get; set; }
        public virtual Courses Courses { get; set; }
        public virtual Users Users { get; set; }
    }
}
