//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeManager.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollegeManagerEntities : DbContext
    {
        private static CollegeManagerEntities _context;
        public CollegeManagerEntities()
            : base("name=CollegeManagerEntities")
        {
        }
        public static CollegeManagerEntities GetContext()
        {
            if (_context == null)
                _context = new CollegeManagerEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademicSheets> AcademicSheets { get; set; }
        public virtual DbSet<AssignmentComments> AssignmentComments { get; set; }
        public virtual DbSet<Assignments> Assignments { get; set; }
        public virtual DbSet<ChatParticipants> ChatParticipants { get; set; }
        public virtual DbSet<Chats> Chats { get; set; }
        public virtual DbSet<CourseMembers> CourseMembers { get; set; }
        public virtual DbSet<CourseResources> CourseResources { get; set; }
        public virtual DbSet<CourseRoles> CourseRoles { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<StudyModules> StudyModules { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
